version: "3.1"
services:
  api:
    image: Mili/api:1.0
    command: sh -c 'npm install; npm start' 
    ports:
      - 6060:6060
    restart: always
    links:
      - 'mongo'
    stdin_open: true
    tty: true
    depends_on:
      - mongo
  web: 
    image: Mili/react-web:1.0
    command: sh -c 'npm install; npm start'
    ports: 
      - 3000:3000
    restart: always
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: mongo
    volumes:
      - ./iniciar-collecion.js:/docker-entrypoint-initdb.d/iniciar-collecion.js:ro
    ports:
      - 27017:27017
    command: ["mongod", "--bind_ip", "0.0.0.0"]
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH: 'false'
